set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports key]


# digital tube
set_property PACKAGE_PIN B4 [get_ports {out[0]}]
set_property PACKAGE_PIN A4 [get_ports {out[1]}]
set_property PACKAGE_PIN A3 [get_ports {out[2]}]
set_property PACKAGE_PIN B1 [get_ports {out[3]}]
set_property PACKAGE_PIN A1 [get_ports {out[4]}]
set_property PACKAGE_PIN B3 [get_ports {out[5]}]
set_property PACKAGE_PIN B2 [get_ports {out[6]}]
set_property PACKAGE_PIN D5 [get_ports {out[7]}]
set_property PACKAGE_PIN G2 [get_ports {led[3]}]
set_property PACKAGE_PIN C2 [get_ports {led[2]}]
set_property PACKAGE_PIN C1 [get_ports {led[1]}]
set_property PACKAGE_PIN H1 [get_ports {led[0]}]

set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN U4 [get_ports key]